version: '3.8'

services:
  llm-api:
    build: .
    ports:
      - "8000:8000"  # vLLM server
      - "8001:8001"  # FastAPI app
    environment:
      - ALLOWED_API_KEYS=sk-1234567890abcdef1234567890abcdef,sk-abcdef1234567890abcdef1234567890
      - API_KEYS_FILE=/app/api_keys.txt
    volumes:
      - ./logs:/app/logs
      - ./out:/app/models  # Mount models directory
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
